### PR TITLE
[SOLVED] Used old bximage version

### PR DESCRIPTION
**Pull request by cakehonolulu**
EDIT: Used an old bximage version

### CODE REVIEW

**Comment by SilverRainZ** [comment]
What is "fail to create hd image"? Please provide more details.

**Comment by cakehonolulu** [comment]
Newer bximage binary versions, adopted a new way for passing image creation arguments to the main program.
Executing 'bximage bin/rootfs.img -hd=10M -imgmode=flat -mode=create -q' no longer works (Displays 'No option named: -hd=10M' or 'No option named -imgmode=flat' etc...)
I looked up a bit and found they changed the way you feed the arguments to bximage, so I thought a pull request would be useful to you.

**Comment by SilverRainZ** [comment]
Are you really sure your bochs is up-to-date? Please refer to #11,  you can see the `-mode=flat -size=10M` options are deprecated, instead the `-hd=10M -imgmode=flat` options are now in use.

Please provide your bochs version if you are still in doubt, note that OS67 requires **2.6.7** or aboved.

**Comment by cakehonolulu** [comment]
Indeed, my fault!
Thanks for pointing out the versioning scheme!
Good luck with your project and have a nice/day!

**Pull request closed without merging**
